"""Writes reports/stage3_policy_gap_<label>.{md,json}."""
from __future__ import annotations

import json
from collections import Counter

from aip.evals import Case, EvalReport

from regtech.gap_eval import GAP, TARGETS, diagnose, target_finding
from regtech.paths import REPORTS_DIR
from regtech.policy_gap import GapReport


def _mean(results, key) -> float:
    vals = [r.metrics[key] for r in results if key in r.metrics]
    return sum(vals) / len(vals) if vals else float("nan")


def write_report(label: str, cases: list[Case], rep: EvalReport, budget: dict, ev) -> dict:
    by_id = {c.id: c for c in cases}
    res = rep.results
    agg = {k: _mean(res, k) for k in ("requirement_found", "status_exact", "status_exact_original_labels",
                                       "gap_call_correct", "missed_gap", "false_alarm", "policy_evidence_seen",
                                       "policy_cited_right", "needs_review_share")}
    reports = {(c.input["entity"], c.input["topic"]): r.output for c, r in zip(cases, res)}
    per_check_cost = [o["cost_usd"] for o in reports.values() if o]
    rows, diag = [], Counter()
    for r in res:
        c = by_id[r.id]
        f = target_finding(r.output, c.expected["rule"]["evidence"]) if r.output else None
        status = f["status"] if f else "-"
        d = diagnose(r.metrics, status) if not r.error else f"error: {r.error}"
        if d:
            diag[d.split(":")[0]] += 1
        rows.append((r.id, c.input["entity"], c.input["topic"], "/".join(c.expected["expected"]), status,
                     "ok" if not d else d))

    def cell(k, fmt="{:.2f}"):
        v = agg[k]
        return "n/a" if v != v else fmt.format(v)

    out = [
        f"# Stage 3 - check_policy_gap evaluation ({label})", "",
        "Generated by `python -m regtech eval-gap`. Each case names one rule (verbatim evidence phrase),",
        "a company, the topic a user would type, and the acceptable statuses; `aip.evals.run_eval`",
        "runs the tool and the metric locates the finding for that rule. Failures are assigned to the",
        "first pipeline stage that went wrong (Lab 5).", "",
        f"{len(cases)} cases over {len(reports)} distinct (company, topic) checks; "
        f"{sum(c.expected['expected'][0] in GAP for c in cases)} expect a gap, "
        f"{sum(c.expected['expected'][0] == 'met' for c in cases)} expect 'met'.", "",
        "| Metric | Our target | Result |", "|---|---|---|",
        f"| Target rule extracted (requirement_found) | ≥ {TARGETS['requirement_found']:.2f} | {cell('requirement_found')} |",
        f"| Status exactly right | ≥ {TARGETS['status_exact']:.2f} | {cell('status_exact')} |",
        f"| Status right under the original, pre-inspection labels | reported | {cell('status_exact_original_labels')} |",
        f"| Gap / no-gap call right | reported | {cell('gap_call_correct')} |",
        f"| Missed gap (said 'met', but there is a gap) | 0 | {cell('missed_gap')} |",
        f"| False alarm (said gap, but policy meets it) | ≤ {TARGETS['false_alarm']:.2f} | {cell('false_alarm')} |",
        f"| 'met' cases: policy wording shown to assessor | reported | {cell('policy_evidence_seen')} |",
        f"| 'met' cases: right policy clause cited | reported | {cell('policy_cited_right')} |",
        f"| Findings that could not be grounded (needs_review) | reported | {cell('needs_review_share')} |",
        f"| Cost per check (this run) | reported | ${sum(per_check_cost) / max(len(per_check_cost), 1):.4f} "
        f"({budget.get('cached_calls', 0)}/{budget.get('calls', 0)} calls from cache) |",
        "",
        "Gap/no-gap, missed-gap and false-alarm rates skip cases whose acceptable labels span 'met' and a",
        "gap (the rule's wording supports both readings).", "",
        "Missed gaps are the dangerous error: a compliance tool that says 'met' when the policy is",
        "silent gives false assurance. False alarms cost review time. Every quote in every finding is",
        "verified verbatim against its source by the schema itself (aip.llm.structured repair loop).", "",
        "## Where failures happen (Lab 5)", "",
    ]
    if diag:
        out += ["| First stage that failed | Cases |", "|---|---:|"] + [f"| {k} | {v} |" for k, v in sorted(diag.items())]
    else:
        out.append("No failures.")
    out += ["", "## Per case", "", "| Case | Company | Topic | Expected | Got | Diagnosis |", "|---|---|---|---|---|---|"]
    out += [f"| {a} | {b} | {t} | {e} | {g} | {d} |" for a, b, t, e, g, d in rows]
    relabelled = [c for c in cases if "original_expected" in c.expected]
    if relabelled:
        out += ["", "## Labels changed after inspecting the tool's output", "",
                "Each change is a case where reading the tool's cited evidence showed the original label was",
                "wrong or too narrow. The metric above under the original labels shows the effect.", "",
                "| Case | Original | Now | Why |", "|---|---|---|---|"]
        out += [f"| {c.id} | {'/'.join(c.expected['original_expected'])} | {'/'.join(c.expected['expected'])} | "
                f"{c.expected['note']} |" for c in relabelled]
    first = next((r.output for r in res if r.id == "G01" and r.output), None)
    if first:
        out += ["", "## Example report (G01: IIFL, gold loan auctions)", "", "```text",
                GapReport.model_validate(first).render(), "```"]
    out += ["", f"Evaluation cost: ${budget.get('cost_usd', 0):.4f} ({budget.get('calls', 0)} model calls, "
            f"{budget.get('cached_calls', 0)} from cache).", ""]
    (REPORTS_DIR / f"stage3_policy_gap_{label}.md").write_text("\n".join(out), encoding="utf-8")
    (REPORTS_DIR / f"stage3_policy_gap_{label}.json").write_text(json.dumps(
        {"aggregate": agg, "diagnosis": dict(diag), "budget": budget, "rows": rows,
         "per_case": {r.id: r.metrics for r in res},
         "reports": {f"{e} | {t}": o for (e, t), o in reports.items()}}, indent=2, default=str), encoding="utf-8")
    return {"aggregate": agg, "diagnosis": dict(diag), "rows": rows}
