from __future__ import annotations

from pathlib import Path

from regtech.manifest import ManifestRow, load_manifest
from regtech.paths import PROCESSED_DIR, REPORTS_DIR
from regtech.pdf_to_md import convert

PROFILE = {"regulation": "regulation", "internal_policy": "generic", "enforcement": "enforcement"}


def processed_path(row: ManifestRow) -> Path:
    return PROCESSED_DIR / row.doc_type / f"{row.doc_id}.md"


def ingest(only: str | None = None) -> list[dict]:
    rows = load_manifest(check_files=True)
    stats = []
    for row in rows:
        if only and row.doc_id != only:
            continue
        conv = convert(row.path, title=row.title, profile=PROFILE[row.doc_type], doc_id=row.doc_id)
        out = processed_path(row)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(conv.markdown, encoding="utf-8")
        stats.append({
            "doc_id": row.doc_id, "doc_type": row.doc_type, "chars_in": conv.chars_in,
            "chars_out": conv.chars_out, "kept": conv.chars_out / max(conv.chars_in, 1),
            "headings": conv.n_headings, "levels": conv.heading_levels, "tables": conv.n_tables,
        })
        print(f"  {row.doc_id:38} in={conv.chars_in:>7} out={conv.chars_out:>7} "
              f"headings={conv.n_headings:>4} {conv.heading_levels} tables={conv.n_tables}")
    if not only:
        _write_summary(stats)
    return stats


def _write_summary(stats: list[dict]) -> None:
    REPORTS_DIR.mkdir(exist_ok=True)
    lines = [
        "# Stage 1 - Ingestion summary",
        "",
        "Generated by `python -m regtech ingest`. `kept` = output chars / raw extracted chars;",
        "the difference is letterheads, running headers/footers, page numbers, tables of",
        "contents and web chrome removed by `regtech/pdf_to_md.py`.",
        "",
        "| doc_id | type | raw chars | md chars | kept | headings (by level) | tables |",
        "|---|---|---:|---:|---:|---|---:|",
    ]
    for s in stats:
        lv = ", ".join(f"h{k}:{v}" for k, v in s["levels"].items()) or "-"
        lines.append(f"| {s['doc_id']} | {s['doc_type']} | {s['chars_in']:,} | {s['chars_out']:,} | "
                     f"{s['kept']:.0%} | {s['headings']} ({lv}) | {s['tables']} |")
    (REPORTS_DIR / "stage1_ingestion.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
