"""Writes reports/stage2_qa.{md,json} from a Stage 2 evaluation run."""
from __future__ import annotations

import json
from collections import Counter

from aip.config import settings
from aip.evals import Case

from regtech.paths import REPORTS_DIR
from regtech.qa_eval import CALIBRATION_CSV, failure_mode, mean, merged


def _fmt(x: float, digits: int = 3) -> str:
    return "n/a" if x != x else f"{x:.{digits}f}"


def _cost_cell(res: dict) -> str:
    probe = res.get("latency_probe")
    if probe:
        return f"${probe['cost_per_query_usd']:.4f} (uncached, from the latency probe)"
    n = len(res["answers"].results)
    b = res["answers"].budget
    note = " (served from cache on this run)" if b.get("calls") and b.get("cached_calls") == b.get("calls") else ""
    return f"${b.get('cost_usd', 0.0) / n:.4f}{note}" if n else "n/a"


def _latency_cell(res: dict) -> str:
    probe = res.get("latency_probe")
    if probe:
        return (f"{probe['p95_ms']:,.0f} ms (p50 {probe['p50_ms']:,.0f} ms; warm, serial, cache off, "
                f"n={probe['n']}, so p95 ≈ max)")
    return f"{res['answers'].latency_percentile(95):,.0f} ms (parallel answer phase; probe not run)"


def write_report(cases: list[Case], balanced: dict, strict: dict, gold: dict | None,
                 kappa: dict | None, total_budget: dict) -> None:
    kinds = {c.id: c.meta["kind"] for c in cases}
    questions = {c.id: c.input for c in cases}
    per = merged(balanced)
    answerable = [c.id for c in cases if kinds[c.id] == "answerable"]
    graded = [c.id for c in cases if kinds[c.id] != "unanswerable"]
    rf = balanced["refusal"]
    judged = "judge" in balanced
    kappa_note = ("κ pending: hand-label `reports/stage2_judge_calibration.csv`, then run "
                  "`python -m regtech judge-kappa`" if not kappa else
                  ", ".join(f"{k} κ={v['cohens_kappa']:.2f} (n={int(v['n'])})" for k, v in kappa.items()))

    rows = [
        ("Citation validity (every [n] is a real source)", "1.00", _fmt(mean(per[i]["citation_valid"] for i in per))),
        ("Faithfulness (judge)", "≥ 0.90", _fmt(mean(per[i].get("faithfulness") for i in per)) if judged else "not run"),
        ("Correctness on answerable (judge)", "≥ 0.75", _fmt(mean(per[i].get("correctness") for i in answerable)) if judged else "not run"),
        ("Refusal recall", "≥ 4/5",
         f"{_fmt(rf['refusal_recall'], 2)} ({int(rf['refused_correctly'])}/{int(rf['should_refuse_total'])})"),
        ("Refusal precision", "≥ 0.70",
         f"{_fmt(rf['refusal_precision'], 2)} ({int(rf['refused_correctly'])}/{int(rf['refused_total'])})"),
        ("Repair rate", "reported", _fmt(mean(per[i]["repaired"] for i in per))),
        ("Cost per query (generation only)", "≤ $0.01", _cost_cell(balanced)),
        ("p95 end-to-end latency", "≤ 6,000 ms", _latency_cell(balanced)),
    ]
    free = [
        ("Gold passage reached the context", _fmt(mean(per[i].get("evidence_in_context") for i in graded))),
        ("Gold passage was cited", _fmt(mean(per[i].get("evidence_cited") for i in graded))),
        ("Numbers in the answer found in cited sources", _fmt(mean(per[i].get("numbers_supported") for i in per))),
        ("Fell back to refusal after a failed repair", _fmt(mean(per[i]["fell_back"] for i in per))),
        ("Truncated, retried at double token budget", _fmt(mean(per[i].get("budget_doubled", 0.0) for i in per))),
    ]

    out = [
        "# Stage 2 - Grounded Q&A over the regulation corpus",
        "",
        "Generated by `python -m regtech eval-qa`. Lab 4 method on `aip.evals`: phase 1 runs the system",
        "and free deterministic checks (`run_eval`), phase 2 runs the LLM judges over the stored answers",
        "(`run_eval` again), so the system's cost and the judges' cost are reported separately.",
        "",
        f"- Generator: `{settings.models['MAIN']}` (MAIN tier) via `aip.rag.RagPipeline`, dense retrieval",
        "  k=8, top 6 passages to the model, 1 corrective repair, then fail closed to the refusal.",
        f"- Judge: `{settings.models['LARGE']}` (LARGE tier), a different model family from the generator,",
        "  to avoid self-preference bias. " + kappa_note + ".",
        f"- Golden set: {len(cases)} questions = {len(answerable)} answerable, "
        f"{sum(k == 'partial' for k in kinds.values())} partial (part answerable, part not), "
        f"{sum(k == 'unanswerable' for k in kinds.values())} unanswerable (two are deliberate traps).",
        "",
        "## Against the Lab 4 targets (balanced prompt)",
        "",
        "| Metric | Target | Result |", "|---|---|---|",
    ]
    out += [f"| {a} | {b} | {c} |" for a, b, c in rows]
    out += ["", "Refusal numbers rest on 5 unanswerable questions: one case moves recall by 0.20. Treat",
            "them as a direction, not a measurement (Lab 4).", "",
            "### Free, deterministic checks (no judge involved)", "", "| Check | Result |", "|---|---|"]
    out += [f"| {a} | {b} |" for a, b in free]

    # refusal dial
    out += ["", "## The refusal dial (Lab 4 C4)", "",
            "Same pipeline, two prompts: *balanced* answers the supported part of a question and names the",
            "unsupported part; *strict* refuses unless every part is supported.", "",
            "| Prompt | Refused: answerable | Refused: partial | Refused: unanswerable | Recall | Precision |",
            "|---|---:|---:|---:|---:|---:|"]
    for name, res in (("balanced", balanced), ("strict", strict)):
        by_kind = Counter(kinds[i] for i, o in res["outputs"].items() if o["refused"])
        tot = Counter(kinds.values())
        r = res["refusal"]
        out.append(f"| {name} | {by_kind['answerable']}/{tot['answerable']} | {by_kind['partial']}/{tot['partial']} | "
                   f"{by_kind['unanswerable']}/{tot['unanswerable']} | {_fmt(r['refusal_recall'], 2)} | "
                   f"{_fmt(r['refusal_precision'], 2)} |")
    out += ["", "Partial questions, balanced prompt:", ""]
    for i in (x for x in kinds if kinds[x] == "partial"):
        out += [f"- **{i}** \"{questions[i]}\"", f"  > {balanced['outputs'][i]['text']}", ""]

    # decomposition
    if gold:
        gper = merged(gold)
        a = mean(gper[i].get("correctness") for i in answerable if i in gper)
        b = mean(per[i].get("correctness") for i in answerable)
        out += ["## Where the errors come from (Lab 4 E2)", "",
                "The same generator, given the gold passages directly instead of retrieved ones:", "",
                "| | Correctness |", "|---|---:|",
                f"| A: with gold context (generation ceiling) | {_fmt(a)} |",
                f"| B: with retrieved context (the real system) | {_fmt(b)} |",
                f"| Retrieval-attributable loss (A - B) | {_fmt(a - b)} |",
                f"| Generation-attributable loss (1 - A) | {_fmt(1 - a)} |", ""]

    # failure modes
    modes = {i: failure_mode(per[i], kinds[i], balanced["outputs"][i]["refused"]) for i in per}
    tally = Counter(m for m in modes.values() if m)
    out += ["## Failure modes (Lab 4 E3, Lab 5 backlog)", ""]
    if tally:
        out += ["| Failure mode | Count |", "|---|---:|"] + [f"| {m} | {n} |" for m, n in tally.most_common()] + [""]
        for i, m in modes.items():
            if m:
                o = balanced["outputs"][i]
                out += [f"- **{i}** ({m}, correctness {_fmt(per[i].get('correctness', float('nan')), 2)}) "
                        f"\"{questions[i]}\"", f"  > {o['text'][:400]}", ""]
    else:
        out += ["No failures on the golden set.", ""]

    # examples
    out += ["## Example answers", ""]
    for i in ("A06", "A19", "U01"):
        if i in balanced["outputs"]:
            o = balanced["outputs"][i]
            cited = "\n".join(f"    [{s['n']}] {s['label']}" for s in o["sources"] if s["n"] in o["cited"])
            out += [f"**{i}. {questions[i]}**", "", "```text", o["text"], *(["", "Sources:", cited] if cited else []),
                    "```", ""]

    out += ["## Cost of this evaluation run", "",
            "Anything already in the aip cache costs $0 on a re-run, so these are this run's marginal costs.", "",
            f"- Generation, balanced: ${balanced['answers'].budget.get('cost_usd', 0):.4f}; strict: "
            f"${strict['answers'].budget.get('cost_usd', 0):.4f}",
            f"- Judging: ${balanced.get('judge').budget.get('cost_usd', 0) if judged else 0:.4f}"
            + (f"; gold-context run incl. judging: ${gold['answers'].budget.get('cost_usd', 0) + gold['judge'].budget.get('cost_usd', 0):.4f}" if gold else ""),
            f"- Total: ${total_budget.get('cost_usd', 0):.4f} ({total_budget.get('calls', 0)} model calls, "
            f"{total_budget.get('cached_calls', 0)} from cache)", ""]
    (REPORTS_DIR / "stage2_qa.md").write_text("\n".join(out) + "\n", encoding="utf-8")

    def slim(res: dict | None) -> dict | None:
        if not res:
            return None
        return {"per_case": merged(res), "budget": res["answers"].budget,
                "outputs": {i: {**o, "sources": [{k: v for k, v in s.items() if k != "text"} for s in o["sources"]]}
                            for i, o in res["outputs"].items()},
                "refusal": res.get("refusal")}
    (REPORTS_DIR / "stage2_qa.json").write_text(json.dumps(
        {"balanced": slim(balanced), "strict": slim(strict), "gold": slim(gold), "kappa": kappa,
         "calibration_sheet": str(CALIBRATION_CSV.name), "total_budget": total_budget}, indent=2, default=str),
        encoding="utf-8")
