"""Greedy one-axis-at-a-time sweep per corpus (Lab 3's search.py, for three corpora).

Order: chunking strategy -> chunk size -> heading-prefix ablation -> retriever.
Each configuration is one aip.evals.run_eval; each step is one aip.evals.compare.
"""
from __future__ import annotations

import json
from dataclasses import asdict

from aip.evals import compare

from regtech.index import IndexConfig
from regtech.paths import REPORTS_DIR
from regtech.retrieval_eval import HEADLINE, Run, evaluate, load_queries

PRIMARY = {"regulation": "ndcg@10", "internal_policy": "ndcg@10", "enforcement": "mrr"}
CORPORA = ("regulation", "internal_policy", "enforcement")


def _best(runs: list[Run], metric: str) -> Run:
    return max(runs, key=lambda r: (round(r.metrics[metric], 4), round(r.metrics["ndcg@10"], 4),
                                    round(r.metrics["mrr"], 4), -r.n_chunks))


def sweep_corpus(doc_type: str) -> dict:
    cases = load_queries(doc_type)
    metric = PRIMARY[doc_type]
    done: dict[str, Run] = {}
    steps: dict[str, list[str]] = {}

    def run(cfg: IndexConfig) -> Run:
        if cfg.label not in done:
            r = done[cfg.label] = evaluate(doc_type, cfg, cases)
            m = r.metrics
            print(f"  {doc_type:15} {cfg.label:28} chunks={r.n_chunks:>5} "
                  + " ".join(f"{k}={m[k]:.3f}" for k in HEADLINE) + f" build=${r.build['cost_usd']:.4f}")
        return done[cfg.label]

    strategies = ["fixed", "sliding", "recursive", "markdown"] + (["whole"] if doc_type == "enforcement" else [])
    a = [run(IndexConfig(s, 0 if s == "whole" else 800, "dense")) for s in strategies]
    steps["A. chunking strategy @800, dense"] = [r.config.label for r in a]
    best = _best(a, metric)

    if best.config.strategy != "whole":
        sizes = [run(IndexConfig(best.config.strategy, s, "dense")) for s in (400, 800, 1600)]
        steps[f"B. chunk size for {best.config.strategy}"] = [r.config.label for r in sizes]
        best = _best(sizes, metric)
        if best.config.strategy == "markdown":
            ablation = run(IndexConfig("markdown_noprefix", best.config.size, "dense"))
            steps["C. heading-path prefix ablation"] = [best.config.label, ablation.config.label]

    retr = [run(IndexConfig(best.config.strategy, best.config.size, kind)) for kind in ("dense", "bm25", "hybrid")]
    steps["D. retriever"] = [r.config.label for r in retr]
    winner = _best(retr, metric)

    return {"corpus": doc_type, "primary_metric": metric, "cases": cases, "winner": winner,
            "steps": steps, "runs": done}


def _run_json(r: Run) -> dict:
    d = r.report.to_dict()
    for res in d["results"]:
        res["output"] = [{**hit, "text": hit["text"][:200]} for hit in (res["output"] or [])[:3]]
    return {"config": asdict(r.config), "n_chunks": r.n_chunks, "build": r.build, "report": d}


def write_report(results: list[dict]) -> None:
    REPORTS_DIR.mkdir(exist_ok=True)
    (REPORTS_DIR / "stage1_retrieval.json").write_text(json.dumps(
        [{"corpus": res["corpus"], "primary_metric": res["primary_metric"], "winner": res["winner"].config.label,
          "steps": res["steps"], "runs": {k: _run_json(v) for k, v in res["runs"].items()}} for res in results],
        indent=2, default=str), encoding="utf-8")

    out = [
        "# Stage 1 - Retrieval evaluation",
        "",
        "Generated by `python -m regtech eval-retrieval`. Each configuration is one `aip.evals.run_eval`",
        "over the corpus's golden set; each table below is `aip.evals.compare` over one sweep step",
        "(`*` = best). Lab 3 method: sweep one axis at a time (strategy -> size -> heading-prefix",
        "ablation -> retriever), fix the winner, move on. A greedy sweep can miss interactions.",
        "",
        "**Relevance labels** (`data/eval/retrieval_*.jsonl`) name each relevant passage by a verbatim",
        "evidence phrase and are scored with `aip.evals.evidence_retrieval_metrics`, so every chunking",
        "strategy is judged against the same ground truth at chunk rank. Enforcement labels are",
        "document-level (Lab 3 de-duplication). Policy queries are scoped to one company's Code with",
        "`aip.retrieval` `chunk_filter`, which is how `check_policy_gap` will search.",
        "",
        "Embedding model `gemini/gemini-embedding-001`. `build $` = embedding spend for that",
        "configuration's chunks on first build; every re-build is $0 from the aip cache.",
        "",
    ]
    for res in results:
        runs: dict[str, Run] = res["runs"]
        out += [f"## {res['corpus']} ({len(res['cases'])} queries) - selection metric `{res['primary_metric']}`", ""]
        for step, labels in res["steps"].items():
            out += [f"### {step}", "", "```text", compare(*(runs[x].report for x in labels), metrics=list(HEADLINE)),
                    "```", "", "| config | chunks | build $ | case p95 ms |", "|---|---:|---:|---:|"]
            out += [f"| {x} | {runs[x].n_chunks} | {runs[x].build['cost_usd']:.4f} | "
                    f"{runs[x].report.latency_percentile(95):.0f} |" for x in labels]
            out.append("")
        kinds = sorted({c.meta["kind"] for c in res["cases"]})
        out += ["### MRR by query kind (retriever step)", "", "| config | " + " | ".join(kinds) + " |",
                "|---|" + "---:|" * len(kinds)]
        for x in res["steps"]["D. retriever"]:
            bd = runs[x].report.breakdown(res["cases"], "kind", "mrr")
            out.append(f"| {x} | " + " | ".join(f"{bd.get(k, float('nan')):.3f}" for k in kinds) + " |")
        w = res["winner"]
        out += ["", f"**Winner: `{w.config.label}`** - " + ", ".join(f"{k}={w.metrics[k]:.3f}" for k in HEADLINE), ""]
        weak = [r for r in w.report.failures("mrr", limit=50) if r.metrics.get("mrr", 0) < 1.0]
        if weak:
            queries = {c.id: c.input["query"] for c in res["cases"]}
            out += ["Queries the winner does not rank first (`EvalReport.failures`) - inputs to Lab 5-style diagnosis:", ""]
            out += [f"- **{r.id}** MRR {r.metrics['mrr']:.2f} \"{queries[r.id]}\" - top hit `{r.output[0]['chunk_id']}`"
                    for r in weak]
            out.append("")
    (REPORTS_DIR / "stage1_retrieval.md").write_text("\n".join(out) + "\n", encoding="utf-8")


def main(corpora: tuple[str, ...] = CORPORA) -> list[dict]:
    results = []
    for c in corpora:
        print(f"== {c}")
        results.append(sweep_corpus(c))
    write_report(results)
    for r in results:
        print(f"winner {r['corpus']:15} {r['winner'].config.label}")
    return results
